version: '3'

services:
  web-ui-service:
    container_name: web-ui-service
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/usr/src/app'
      - '/usr/src/app/node_modules'
    ports:
      - '3000:3000'
    depends_on:
      - restaurant-data-service
    networks:
      vegitable_net:
        ipv4_address: 173.29.1.1

  mysql:  
    image: mysql:5.7
    container_name: mysql
    volumes:
      - mysql-volume:/var/lib/mysql
    ports: 
      - 3306:3306
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: '999apple%'
      MYSQL_DATABASE: userauthenticationdb
      MYSQL_USER: root
      MYSQL_PASSWORD: '999apple%'
    networks:
      vegitable_net:
        ipv4_address: 173.29.1.3

  user-data-service:
    image: timhaydenhawkins/user-data-service
    ports: 
      - 3002:3002
    restart: always
    depends_on:
      - mysql
    command: ["npm", "start"]
    networks:
      vegitable_net:
        ipv4_address: 173.29.1.4

  restaurant-data-service:
    image: timhaydenhawkins/restaurant-data-service
    environment:
      CORSHEADER: http://localhost:3000
    ports:
      - 3001:3001
    networks:
      vegitable_net:
        ipv4_address: 173.29.1.2

volumes:
  mysql-volume:

networks:
  vegitable_net:
    ipam:
      driver: default
      config:
        - subnet: 173.29.0.0/16

  