version: '3'

services:
  web-ui-service:
    container_name: web-ui-service
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/usr/src/app'
      - '/usr/src/app/node_modules'
    ports:
      - '3000:3000'
    depends_on:
      - restaurant-data-service
    networks:
      vegitable_net:
        ipv4_address: 173.29.1.1

  user-data-service:
    image: timhaydenhawkins/user-data-service
    container_name: user-data-service
    environment:
      CORSHEADER: http://localhost:3000
    ports: 
      - 3002:3002
    restart: always
    command: ["npm", "start"]
    networks:
      vegitable_net:
        ipv4_address: 173.29.1.4

  restaurant-data-service:
    image: timhaydenhawkins/restaurant-data-service
    container_name: restaurant-data-service
    environment:
      CORSHEADER: http://localhost:3000
    ports:
      - 3001:3001
    networks:
      vegitable_net:
        ipv4_address: 173.29.1.2

networks:
  vegitable_net:
    ipam:
      driver: default
      config:
        - subnet: 173.29.0.0/16

  